# https://travis-ci.org/#!/translate/pootle
sudo: false
language: python
#env:
#  - TOXENV=py27 PYTHONPATH=$HOME/virtualenv/python2.7.9/lib/python2.7/site-packages TOX_TESTENV_PASSENV="PYTHONPATH"
#  - TOXENV=py33 PYTHONPATH=$HOME/virtualenv/python2.7.9/lib/python2.7/site-packages TOX_TESTENV_PASSENV="PYTHONPATH"
#  - TOXENV=py34 PYTHONPATH=$HOME/virtualenv/python2.7.9/lib/python2.7/site-packages TOX_TESTENV_PASSENV="PYTHONPATH"
#  - TOXENV=py35 PYTHONPATH=$HOME/virtualenv/python2.7.9/lib/python2.7/site-packages TOX_TESTENV_PASSENV="PYTHONPATH"
matrix:
    include:
      - python: 2.7
        env: TOXENV=py27
      - python: 3.3
        env: TOXENV=py33
      - python: 3.4
        env: TOXENV=py34
      - python: 3.5 # not yet pre-installed in Travis base image
        env: TOXENV=py35
install:
  - pip install tox
script:
  - tox -e $TOXENV
